AWSTemplateFormatVersion: '2010-09-09'
Resources:
  NetworkStack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: 'https://childstacksri.s3.amazonaws.com/networkstack.yaml'