Parameters:
  SSHKey:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Name of an existing EC2 key pair to enable SSH access to the instance

  VpcCIDR:
    Type: String
    Default: 10.0.0.0/16
    Description: Please enter VPC CIDR
  
  SubnetCIDR:
    Type: String
    Default: 10.0.1.0/24
    Description: Please Enter CIDR for Subnet

Resources:
  myVPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://cf-templates-1vmfbc9sv7pra-us-east-1.s3.amazonaws.com/vpc-stack+-withmetadata
      Parameters:
        VpcCIDR: !Ref VpcCIDR
        SubnetCIDR: !Ref SubnetCIDR

  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: us-east-1a
      ImageId: ami-00b8917ae86a424c9  
      InstanceType: t2.micro
      KeyName: !Ref SSHKey  
      NetworkInterfaces: 
      - AssociatePublicIpAddress: "true"
        DeviceIndex: "0"
        SubnetId: !GetAtt myVPCStack.Outputs.mySubnet
      UserData:
        Fn::Base64:
          !Sub |
            #!/bin/bash -xe
            yum update -y
            yum install -y httpd
            systemctl start httpd
            systemctl enable httpd
            echo "Hello world from srilata" > /var/www/html/index.html

Outputs:
  AppURL:
    Description: Application URL to access
    Value: !Sub 'http://${MyInstance.PublicDnsName}:8080/index.html'
